/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "EmailApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "EmailApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WebSite": {
      "type": "sst.cloudflare.StaticSite"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}